import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import ChanelLogo from "@/public/chanel.jpg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Black header bar */}
        <div className="w-full bg-black h-25 flex-row justify-between gap-10 flex items-center px-5">
          <Image
            src={ChanelLogo}
            alt="Chanel Logo"
            className="object-contain"
            priority
            width={100}
            height={100}
          />

          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Button className="overflow-hidden h-32 p-0 bg-black">
              <Image
                src={
                  "https://ok4static.oktacdn.com/fs/bco/1/fs012r07i1rX4ZtdW1t8"
                }
                alt="Coupa Logo"
                className="object-contain"
                priority
                width={160}
                height={50}
                style={{
                  padding: "10px",
                  backgroundColor: "white",
                  borderRadius: "10px",
                }}
              />
            </Button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
